/**
 * What a tenant submission must look like, for both the wizard and the server
 * action that receives it.
 *
 * It lives here rather than beside the action so the browser can apply the
 * same rules while the operator is still filling the form. Several of them are
 * things the cloud only objects to much later: a slug too long for the names
 * AWS builds from it fails an apply after the load balancer already exists,
 * and a certificate from the wrong region fails minutes into a workflow run.
 * The server still re-parses everything, since nothing arriving over the wire
 * is trustworthy; the shared copy only moves the complaint earlier.
 */
import { z } from "zod";

const UUID_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

// ── Shared fields ─────────────────────────────────────────────────────
const SharedInput = z.object({
  // Generated by the platform when the wizard opens, not typed, and required on
  // both clouds: the customer's trust is bound to it before the tenant exists —
  // as the GitHub environment in an Azure federated credential's subject, and as
  // the sts:ExternalId in an AWS role's trust policy. A tenant created under any
  // other ID would be one nothing trusts.
  tenantId: z.string().regex(UUID_RE, "The tenant ID was lost. Reload the page and start again."),
  cloudProvider: z.enum(["aws", "azure"]),
  name: z.string().min(1, "Required").max(100),
  slug: z
    .string()
    .min(3, "Must be at least 3 characters")
    // Every cloud resource is named after this, and the shortest ceiling wins.
    // On AWS the frontend's target group is chatbot-<slug>-ui and AWS caps
    // that name at 32 characters, so the slug cannot exceed 21. Azure's Key
    // Vault is tighter still, and is checked per cloud below.
    .max(21, "Must be 21 characters or fewer, since cloud resource names are built from it")
    .regex(
      /^[a-z0-9][a-z0-9-]*[a-z0-9]$/,
      "Lowercase letters, numbers, and hyphens only; cannot start or end with a hyphen"
    ),
  chatbotVersion: z.string().min(1).default("latest"),
  domain: z
    .string()
    .refine(
      (v) => v === "" || /^([a-zA-Z0-9-]+\.)+[a-zA-Z]{2,}$/.test(v),
      "Must be a valid hostname (e.g. chat.example.com) — no https:// or trailing slash"
    )
    .optional(),
  llmProvider: z.enum(["openai", "anthropic", "openrouter"], {
    message: "Select a provider",
  }),
  llmApiKey: z.string().min(10, "API key looks too short"),
  llmModel: z.string().optional(),
  vectorStore: z.enum(["pinecone", "pgvector"]).default("pinecone"),
  // Required only for vectorStore = "pinecone"; enforced by the refine below.
  pineconeApiKey: z.string().optional(),
});

// ── AWS fields ────────────────────────────────────────────────────────

/**
 * Regions where S3 offers no account-regional namespace. Each AWS tenant's
 * Terraform state lives in a bucket in that namespace, which is what stops
 * another account from registering the bucket's predictable name first, so a
 * tenant in these regions would have nowhere safe to keep its state.
 */
export const AWS_REGIONS_WITHOUT_STATE_BUCKETS = ["me-south-1", "me-central-1"];

const AwsInput = SharedInput.extend({
  cloudProvider: z.literal("aws"),
  awsAccountId: z.string().regex(/^\d{12}$/, "Must be exactly 12 digits"),
  awsRegion: z
    .string()
    .regex(/^[a-z]{2}-[a-z]+-[0-9]$/, "Must be a valid AWS region (e.g. us-east-1)"),
  deploymentRoleArn: z
    .string()
    .regex(/^arn:aws:iam::\d{12}:role\/.+$/, "Must be a valid IAM role ARN"),
  s3DocsPrefix: z
    .string()
    .refine((v) => !v.startsWith("/"), "Must not start with a leading slash")
    .optional(),
  // Optional, but it is the only thing that gets a tenant TLS: without it the
  // ALB listens on port 80 only and every question and answer crosses the
  // internet in clear text.
  acmCertificateArn: z
    .string()
    .refine(
      (v) => v === "" || /^arn:aws:acm:[a-z0-9-]+:\d{12}:certificate\/.+$/.test(v),
      "Must be a valid ACM certificate ARN (arn:aws:acm:REGION:ACCOUNT:certificate/ID)",
    )
    .optional(),
});

// ── Azure fields ──────────────────────────────────────────────────────

// All three Azure identifiers are UUIDs, and the deploy's own Terraform
// validates them as such. Checking here too means a value pasted into the
// wrong box is rejected on the form, rather than surfacing minutes later as
// an opaque Entra error (AADSTS700016) from the middle of a workflow run.
const azureUuid = (label: string) =>
  z.string().regex(UUID_RE, `${label} must be a valid UUID`);

// No client secret. The customer's identity trusts the deploy workflow through
// a federated credential instead (see src/lib/azureFederation.ts), so the
// platform never holds anything that can sign in to their subscription.
const AzureInput = SharedInput.extend({
  cloudProvider: z.literal("azure"),
  azureSubscriptionId: azureUuid("Subscription ID"),
  azureTenantId: azureUuid("Azure AD Tenant ID"),
  azureClientId: azureUuid("Client ID"),
  azureRegion: z.string().min(1, "Required"),
});

// The Pinecone key is the customer's own, so it is mandatory when they pick
// Pinecone and unused when the vectors stay inside their cloud account.
export const TenantInput = z
  .discriminatedUnion("cloudProvider", [AwsInput, AzureInput])
  .refine((v) => v.vectorStore !== "pinecone" || (v.pineconeApiKey ?? "").length >= 10, {
    message: "Required when the vector store is Pinecone",
    path: ["pineconeApiKey"],
  })
  // A certificate with no domain would open port 443 for a hostname nobody
  // resolves, while the tenant's advertised URL stayed on plain HTTP.
  .refine((v) => v.cloudProvider !== "aws" || !v.acmCertificateArn || Boolean(v.domain), {
    message:
      "A certificate only takes effect together with a custom domain. ACM cannot issue one for the load balancer's own hostname.",
    path: ["acmCertificateArn"],
  })
  // A load balancer can only use certificates from its own region. Caught
  // here because otherwise it surfaces minutes later, as a Terraform error
  // from the middle of a workflow run.
  .refine(
    (v) =>
      v.cloudProvider !== "aws" ||
      !v.acmCertificateArn ||
      v.acmCertificateArn.split(":")[3] === v.awsRegion,
    {
      message:
        "The certificate must live in the same region as the deployment. Request it again in the tenant's region.",
      path: ["acmCertificateArn"],
    },
  )
  .refine(
    (v) => v.cloudProvider !== "aws" || !AWS_REGIONS_WITHOUT_STATE_BUCKETS.includes(v.awsRegion),
    {
      message:
        "This region cannot hold the chatbot's deployment state in a bucket only your account can own (S3 does not offer account-regional namespaces in Bahrain or the UAE). Choose another region.",
      path: ["awsRegion"],
    },
  )
  // Azure's Key Vault is named cb-<slug>-kv and capped at 24 characters, which
  // is stricter than the shared limit above. Caught here because a slug is
  // permanent: a tenant created too long can never be deployed, only deleted.
  .refine((v) => v.cloudProvider !== "azure" || v.slug.length <= 18, {
    message: "An Azure tenant's slug must be 18 characters or fewer: its Key Vault is named cb-<slug>-kv.",
    path: ["slug"],
  });

/** The wizard's working copy: every field a string, and absent until typed. */
export type TenantValues = Record<string, string | undefined>;

/**
 * Shapes raw form values for the schema. Optional fields become undefined when
 * blank, so an untouched box is "not given" rather than "given as empty", and
 * the two fields with defaults get them.
 */
export function rawTenantInput(values: TenantValues) {
  const optional = (key: string) => values[key] || undefined;

  return {
    tenantId: optional("tenantId"),
    cloudProvider: values.cloudProvider ?? null,
    name: values.name ?? null,
    slug: values.slug ?? null,
    chatbotVersion: values.chatbotVersion || "latest",
    domain: optional("domain"),
    llmProvider: values.llmProvider ?? null,
    llmApiKey: values.llmApiKey ?? null,
    llmModel: optional("llmModel"),
    vectorStore: values.vectorStore || "pinecone",
    pineconeApiKey: optional("pineconeApiKey"),
    // AWS
    awsAccountId: values.awsAccountId ?? null,
    awsRegion: values.awsRegion ?? null,
    deploymentRoleArn: values.deploymentRoleArn ?? null,
    s3DocsPrefix: optional("s3DocsPrefix"),
    acmCertificateArn: optional("acmCertificateArn"),
    // Azure
    azureSubscriptionId: values.azureSubscriptionId ?? null,
    azureTenantId: values.azureTenantId ?? null,
    azureClientId: values.azureClientId ?? null,
    azureRegion: values.azureRegion ?? null,
  };
}

/**
 * Field errors for values that are still being filled in.
 *
 * `fields` narrows the answer to one step's inputs, because a half-finished
 * form always fails on the steps ahead of the operator and complaining about
 * those would be noise. Omit it to check the whole submission.
 */
export function validateTenantValues(
  values: TenantValues,
  fields?: readonly string[],
): Record<string, string> {
  const result = TenantInput.safeParse(rawTenantInput(values));
  if (result.success) return {};

  const errors: Record<string, string> = {};
  for (const issue of result.error.issues) {
    const field = String(issue.path[issue.path.length - 1]);
    if (fields && !fields.includes(field)) continue;
    if (!errors[field]) errors[field] = issue.message;
  }
  return errors;
}
