import { describe, it, expect, beforeEach, vi } from "vitest";
import { buildFormData } from "@/test/form-data";

const {
  authMock,
  dbInsertValues,
  dbInsertReturning,
  dbUpdateValues,
  dbUpdateReturning,
  triggerDeployment,
  encryptSecret,
  assumeTenantRole,
  writeTenantSecret,
  ensureDocsSignerSecret,
  generateDocsSignerSecret,
  redirectMock,
  revalidatePathMock,
  dbSelectLimit,
} = vi.hoisted(() => {
    // What a lookup finds — the slug's, then the deployment identity's. Empty
    // means the value belongs to no other tenant.
    const dbSelectLimit = vi.fn<(n: number) => Promise<Record<string, unknown>[]>>(async () => []);
    const authMock = vi.fn();
    const dbInsertReturning = vi.fn();
    // Declared here (rather than via insertValuesReturningChain) so tests can
    // assert on the row actually handed to drizzle, not just that it inserted.
    // The signature is supplied as a type argument so `mock.calls` is typed
    // without the implementation needing an unused parameter.
    const dbInsertValues = vi.fn<(row: unknown) => { returning: typeof dbInsertReturning }>(
      () => ({ returning: dbInsertReturning }),
    );
    const dbUpdateReturning = vi.fn();
    // Same rationale as dbInsertValues: kept as a stable mock (not a fresh
    // chain per call) so saveTenantDraft's update-path tests can inspect the
    // row it actually passed to drizzle, e.g. confirming secret fields never
    // reach `.set(...)`.
    const dbUpdateValues = vi.fn<
      (row: unknown) => { where: () => { returning: typeof dbUpdateReturning } }
    >(() => ({ where: () => ({ returning: dbUpdateReturning }) }));
    const triggerDeployment = vi.fn();
    const encryptSecret = vi.fn((v: string) => `enc:${v}`);
    const assumeTenantRole = vi.fn();
    const writeTenantSecret = vi.fn();
    const ensureDocsSignerSecret = vi.fn();
    const generateDocsSignerSecret = vi.fn();
    const redirectMock = vi.fn((url: string) => {
      throw new Error(`REDIRECT:${url}`);
    });
    const revalidatePathMock = vi.fn();
    return {
      dbSelectLimit,
      revalidatePathMock,
      authMock,
      dbInsertValues,
      dbInsertReturning,
      dbUpdateValues,
      dbUpdateReturning,
      triggerDeployment,
      encryptSecret,
      assumeTenantRole,
      writeTenantSecret,
      ensureDocsSignerSecret,
      generateDocsSignerSecret,
      redirectMock,
    };
  });

vi.mock("next/navigation", () => ({ redirect: redirectMock }));
vi.mock("next/cache", () => ({ revalidatePath: revalidatePathMock }));
vi.mock("@/auth", () => ({ auth: authMock }));
vi.mock("@/db", () => ({
  db: {
    // The slug lookup: select().from(tenants).where(...).limit(1).
    select: vi.fn(() => ({ from: () => ({ where: () => ({ limit: dbSelectLimit }) }) })),
    insert: vi.fn(() => ({ values: dbInsertValues })),
    update: vi.fn(() => ({ set: dbUpdateValues })),
    // Only reached when the wizard submits a draftId; stubbed so the
    // post-deploy draft cleanup doesn't blow up the success-path tests.
    delete: vi.fn(() => ({ where: vi.fn().mockResolvedValue(undefined) })),
  },
}));
vi.mock("@/lib/deploy", () => ({ triggerDeployment }));
vi.mock("@/lib/crypto", () => ({ encryptSecret }));
vi.mock("@/lib/aws", () => ({ assumeTenantRole, writeTenantSecret, ensureDocsSignerSecret }));
vi.mock("@/lib/azure", () => ({ generateDocsSignerSecret }));

import { db } from "@/db";
import { tenantDrafts } from "@/db/schema";
import {
  checkDeploymentIdentity,
  checkSlugAvailable,
  createTenantAndDeploy,
  saveTenantDraft,
  deleteTenantDraft,
} from "./actions";

function formData(fields: Record<string, string | undefined>): FormData {
  return buildFormData(fields);
}

/** The row handed to `db.insert(tenants).values(...)` by the last call. */
function insertedValues(): Record<string, unknown> {
  const calls = dbInsertValues.mock.calls;
  return calls[calls.length - 1][0] as Record<string, unknown>;
}

/** The row handed to `db.update(tenantDrafts).set(...)` by the last call. */
function updatedValues(): Record<string, unknown> {
  const calls = dbUpdateValues.mock.calls;
  return calls[calls.length - 1][0] as Record<string, unknown>;
}

const validAws = {
  // Generated by the wizard before the tenant exists, because the customer's
  // trust policy conditions on it as the sts:ExternalId.
  tenantId: "7c1f9a52-3e84-4b16-9d27-0af5c6e81b34",
  cloudProvider: "aws",
  name: "Acme Co",
  slug: "acme-co",
  chatbotVersion: "latest",
  domain: "chat.acme.com",
  llmProvider: "openai",
  llmApiKey: "sk-1234567890",
  llmModel: "gpt-4o",
  vectorStore: "pinecone",
  pineconeApiKey: "pc-1234567890",
  awsAccountId: "123456789012",
  awsRegion: "us-east-1",
  deploymentRoleArn: "arn:aws:iam::123456789012:role/deploy",
  s3DocsPrefix: "docs/",
};

const validAzure = {
  cloudProvider: "azure",
  name: "Beta Co",
  slug: "beta-co",
  chatbotVersion: "latest",
  domain: "chat.beta.com",
  llmProvider: "anthropic",
  llmApiKey: "sk-ant-1234567890",
  llmModel: "claude-sonnet",
  vectorStore: "pgvector",
  azureSubscriptionId: "12345678-1234-1234-1234-123456789012",
  azureTenantId: "22222222-2222-2222-2222-222222222222",
  azureClientId: "33333333-3333-3333-3333-333333333333",
  azureRegion: "eastus",
  tenantId: "0b6f3c7e-9a1d-4a7e-8f53-2d1c6b9e4a10",
};

describe("createTenantAndDeploy", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    authMock.mockResolvedValue({ user: { id: "user-1" } });
    dbInsertReturning.mockResolvedValue([{ id: "tenant-1" }]);
    triggerDeployment.mockResolvedValue({
      id: "deploy-1",
      startedAt: new Date("2026-01-01T00:00:00Z"),
    });
    encryptSecret.mockImplementation((v: string) => `enc:${v}`);
    assumeTenantRole.mockResolvedValue({
      accessKeyId: "a",
      secretAccessKey: "b",
      sessionToken: "c",
    });
    writeTenantSecret.mockResolvedValue("arn:aws:secretsmanager:us-east-1:123456789012:secret:x");
    ensureDocsSignerSecret.mockResolvedValue({
      docsSignerSecretArn: "arn:aws:secretsmanager:us-east-1:123456789012:secret:acme-co/docs-signer-secret",
      docsSignerSecretEncrypted: "enc:docs-signer-secret",
    });
    generateDocsSignerSecret.mockReturnValue({
      docsSignerSecretEncrypted: "enc:azure-docs-signer-secret",
      docsSignerSecretPlaintext: "azure-plaintext-secret",
    });
  });

  it("redirects to /signin when there is no authenticated session", async () => {
    authMock.mockResolvedValue(null);

    await expect(createTenantAndDeploy(null, formData(validAws))).rejects.toThrow("REDIRECT:/signin");
    expect(db.insert).not.toHaveBeenCalled();
  });

  // A taken slug used to be caught only by the insert — after AWS onboarding
  // had already written secrets named after it into the customer's account.
  it("refuses a slug already in use before anything reaches the customer's cloud", async () => {
    dbSelectLimit.mockResolvedValueOnce([{ id: "older-tenant" }]);

    const result = await createTenantAndDeploy(null, formData(validAws));

    expect(result?.errors.slug).toMatch(/Slugs are permanent/);
    expect(assumeTenantRole).not.toHaveBeenCalled();
    expect(writeTenantSecret).not.toHaveBeenCalled();
    expect(ensureDocsSignerSecret).not.toHaveBeenCalled();
    expect(db.insert).not.toHaveBeenCalled();
    expect(triggerDeployment).not.toHaveBeenCalled();
  });

  // Each chatbot's setup creates its own identity. One another tenant used —
  // here an old app registration, entered for chatbot after chatbot — could
  // only fail at sign-in, after a check or a deploy had been dispatched.
  it("refuses an Azure identity another chatbot used, naming that chatbot", async () => {
    dbSelectLimit
      .mockResolvedValueOnce([]) // the slug is free
      .mockResolvedValueOnce([{ slug: "product-chatbot", deletedAt: new Date() }]);

    const result = await createTenantAndDeploy(null, formData(validAzure));

    expect(result?.errors.azureClientId).toMatch(/"product-chatbot", which has been deleted/);
    expect(result?.errors.azureClientId).toMatch(/clientId output/);
    expect(db.insert).not.toHaveBeenCalled();
    expect(triggerDeployment).not.toHaveBeenCalled();
  });

  it("refuses an AWS role another chatbot used, before assuming it", async () => {
    dbSelectLimit.mockResolvedValueOnce([]).mockResolvedValueOnce([{ slug: "hr-info-chatbot", deletedAt: null }]);

    const result = await createTenantAndDeploy(null, formData(validAws));

    expect(result?.errors.deploymentRoleArn).toMatch(/"hr-info-chatbot"\./);
    expect(assumeTenantRole).not.toHaveBeenCalled();
    expect(writeTenantSecret).not.toHaveBeenCalled();
    expect(db.insert).not.toHaveBeenCalled();
  });

  describe("shared field validation", () => {
    it("rejects a slug that is too short", async () => {
      const result = await createTenantAndDeploy(null, formData({ ...validAws, slug: "ab" }));
      expect(result?.errors.slug).toMatch(/at least 3 characters/);
    });

    // AWS names the frontend's target group chatbot-<slug>-ui and rejects
    // anything over 32 characters, which a 22-character slug exceeded only
    // once the load balancer already existed.
    it("rejects an AWS slug too long for a target group name", async () => {
      const result = await createTenantAndDeploy(
        null,
        formData({ ...validAws, slug: "company-info-chatbot-1" }),
      );
      expect(result?.errors.slug).toBeDefined();
    });

    it("accepts an AWS slug at the 21-character ceiling", async () => {
      const slug = "company-info-chatbotx";
      expect(slug).toHaveLength(21);

      const result = await createTenantAndDeploy(null, formData({ ...validAws, slug }));
      expect(result?.errors.slug).toBeUndefined();
    });

    it("rejects an Azure slug over 18 characters, which its Key Vault name cannot take", async () => {
      const result = await createTenantAndDeploy(
        null,
        formData({ ...validAzure, slug: "nineteen-characters" }),
      );
      expect(result?.errors.slug).toBeDefined();
    });

    it("rejects a slug with uppercase letters", async () => {
      const result = await createTenantAndDeploy(null, formData({ ...validAws, slug: "Acme-Co" }));
      expect(result?.errors.slug).toBeDefined();
    });

    it("rejects a slug starting with a hyphen", async () => {
      const result = await createTenantAndDeploy(null, formData({ ...validAws, slug: "-acme" }));
      expect(result?.errors.slug).toBeDefined();
    });

    it("rejects an invalid domain", async () => {
      const result = await createTenantAndDeploy(
        null,
        formData({ ...validAws, domain: "https://chat.acme.com/" }),
      );
      expect(result?.errors.domain).toMatch(/valid hostname/);
    });

    it("accepts an empty domain (optional field)", async () => {
      const result = await createTenantAndDeploy(null, formData({ ...validAws, domain: "" }));
      // Empty domain is valid, so this should deploy rather than return a
      // validation-error object.
      expect(result?.errors).toEqual({});
      expect(result?.deployed).toEqual({
        tenantId: "tenant-1",
        deploymentId: "deploy-1",
        startedAt: "2026-01-01T00:00:00.000Z",
      });
    });

    it("rejects an unrecognized llmProvider", async () => {
      const result = await createTenantAndDeploy(
        null,
        formData({ ...validAws, llmProvider: "made-up-provider" }),
      );
      expect(result?.errors.llmProvider).toMatch(/Select a provider/);
    });

    it("rejects an llmApiKey that is too short", async () => {
      const result = await createTenantAndDeploy(null, formData({ ...validAws, llmApiKey: "short" }));
      expect(result?.errors.llmApiKey).toMatch(/too short/);
    });

    it("requires pineconeApiKey when vectorStore is pinecone", async () => {
      const result = await createTenantAndDeploy(
        null,
        formData({ ...validAws, vectorStore: "pinecone", pineconeApiKey: undefined }),
      );
      expect(result?.errors.pineconeApiKey).toMatch(/Required when the vector store is Pinecone/);
    });

    it("does not require pineconeApiKey when vectorStore is pgvector", async () => {
      const result = await createTenantAndDeploy(
        null,
        formData({ ...validAws, vectorStore: "pgvector", pineconeApiKey: undefined }),
      );
      expect(result?.errors).toEqual({});
      expect(result?.deployed).toBeDefined();
    });

    it("rejects an unrecognized cloudProvider", async () => {
      const result = await createTenantAndDeploy(null, formData({ ...validAws, cloudProvider: "gcp" }));
      expect(result?.errors).toBeTruthy();
      expect(Object.keys(result!.errors).length).toBeGreaterThan(0);
    });
  });

  describe("AWS field validation", () => {
    it("rejects an awsAccountId that is not 12 digits", async () => {
      const result = await createTenantAndDeploy(null, formData({ ...validAws, awsAccountId: "123" }));
      expect(result?.errors.awsAccountId).toMatch(/exactly 12 digits/);
    });

    it("rejects a malformed awsRegion", async () => {
      const result = await createTenantAndDeploy(null, formData({ ...validAws, awsRegion: "useast1" }));
      expect(result?.errors.awsRegion).toMatch(/valid AWS region/);
    });

    it("rejects a malformed deploymentRoleArn", async () => {
      const result = await createTenantAndDeploy(
        null,
        formData({ ...validAws, deploymentRoleArn: "not-an-arn" }),
      );
      expect(result?.errors.deploymentRoleArn).toMatch(/valid IAM role ARN/);
    });

    it("rejects an s3DocsPrefix with a leading slash", async () => {
      const result = await createTenantAndDeploy(
        null,
        formData({ ...validAws, s3DocsPrefix: "/docs" }),
      );
      expect(result?.errors.s3DocsPrefix).toMatch(/leading slash/);
    });

    it("rejects a malformed acmCertificateArn", async () => {
      const result = await createTenantAndDeploy(
        null,
        formData({ ...validAws, domain: "chat.acme.com", acmCertificateArn: "not-an-arn" }),
      );
      expect(result?.errors.acmCertificateArn).toMatch(/valid ACM certificate ARN/);
    });

    it("rejects a certificate with no domain, which would listen on 443 for a hostname nobody resolves", async () => {
      const result = await createTenantAndDeploy(
        null,
        formData({
          ...validAws,
          domain: "",
          acmCertificateArn: "arn:aws:acm:us-east-1:123456789012:certificate/abc",
        }),
      );
      expect(result?.errors.acmCertificateArn).toMatch(/custom domain/);
    });

    it("rejects a certificate from another region, which a load balancer cannot use", async () => {
      const result = await createTenantAndDeploy(
        null,
        formData({
          ...validAws,
          awsRegion: "eu-central-1",
          domain: "chat.acme.com",
          acmCertificateArn: "arn:aws:acm:us-east-1:123456789012:certificate/abc",
        }),
      );
      expect(result?.errors.acmCertificateArn).toMatch(/same region/);
    });

    it("accepts a certificate in the deployment region alongside a domain", async () => {
      const result = await createTenantAndDeploy(
        null,
        formData({
          ...validAws,
          awsRegion: "us-east-1",
          domain: "chat.acme.com",
          acmCertificateArn: "arn:aws:acm:us-east-1:123456789012:certificate/abc",
        }),
      );
      expect(result?.errors.acmCertificateArn).toBeUndefined();
    });
  });

  describe("Azure field validation", () => {
    it("rejects a malformed azureSubscriptionId", async () => {
      const result = await createTenantAndDeploy(
        null,
        formData({ ...validAzure, azureSubscriptionId: "not-a-uuid" }),
      );
      expect(result?.errors.azureSubscriptionId).toMatch(/valid UUID/);
    });

    it("rejects an azureClientId that isn't a UUID", async () => {
      // A slug or secret pasted into the client ID box otherwise reaches Azure
      // and fails mid-deploy as AADSTS700016 ("application not found").
      const result = await createTenantAndDeploy(
        null,
        formData({ ...validAzure, azureClientId: "test2206" }),
      );
      expect(result?.errors.azureClientId).toMatch(/valid UUID/);
    });

    it("rejects an azureTenantId that isn't a UUID", async () => {
      const result = await createTenantAndDeploy(
        null,
        formData({ ...validAzure, azureTenantId: "my-directory" }),
      );
      expect(result?.errors.azureTenantId).toMatch(/valid UUID/);
    });

    it("refuses an Azure tenant without the tenant ID its federated credential names", async () => {
      const result = await createTenantAndDeploy(
        null,
        formData({ ...validAzure, tenantId: undefined }),
      );
      expect(result?.errors.tenantId).toBeDefined();
      expect(db.insert).not.toHaveBeenCalled();
    });
  });

  // Provisioning talks to the customer's cloud and to GitHub. Thrown, those
  // failures reach the browser as React's redacted placeholder and the wizard
  // shows a bare 500, so they are returned under "_form" instead — a key the
  // review step owns, so the user stays where they pressed Deploy.
  describe("provisioning failures are returned, not thrown", () => {
    beforeEach(() => {
      vi.spyOn(console, "error").mockImplementation(() => {});
    });

    it("surfaces an AWS SDK error verbatim, since it names the operator's own role", async () => {
      const denied = Object.assign(
        new Error(
          "User: arn:aws:iam::314113910299:user/platform is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::314113910299:role/wrong-role",
        ),
        { name: "AccessDenied", $metadata: { httpStatusCode: 403 } },
      );
      assumeTenantRole.mockRejectedValue(denied);

      const result = await createTenantAndDeploy(null, formData(validAws));

      expect(result?.deployed).toBeUndefined();
      expect(result?.errors._form).toContain("AccessDenied");
      expect(result?.errors._form).toContain("sts:AssumeRole");
      // Nothing may be recorded for a tenant whose cloud setup failed.
      expect(triggerDeployment).not.toHaveBeenCalled();
    });

    it("surfaces a secret still scheduled for deletion, the reused-slug case", async () => {
      writeTenantSecret.mockRejectedValue(
        Object.assign(
          new Error(
            "You can't create this secret because a secret with this name is already scheduled for deletion.",
          ),
          { name: "InvalidRequestException", $metadata: { httpStatusCode: 400 } },
        ),
      );

      const result = await createTenantAndDeploy(null, formData(validAws));

      expect(result?.errors._form).toContain("scheduled for deletion");
      expect(triggerDeployment).not.toHaveBeenCalled();
    });

    it("tells the operator to sign in when the platform has no AWS session of its own", async () => {
      assumeTenantRole.mockRejectedValue(
        Object.assign(
          new Error(
            "Failed to load a token for session arn:aws:iam::229647349798:user/operator, please re-authenticate using aws login",
          ),
          { name: "CredentialsProviderError" },
        ),
      );

      const result = await createTenantAndDeploy(null, formData(validAws));

      expect(result?.errors._form).toContain("aws login");
      // The SDK's own text names a local cache path; only the instruction goes out.
      expect(result?.errors._form).not.toContain("Failed to load a token");
      expect(triggerDeployment).not.toHaveBeenCalled();
    });

    it("surfaces the refusal to call AWS with a long-lived access key", async () => {
      assumeTenantRole.mockRejectedValue(
        Object.assign(
          new Error(
            "The platform refuses to call AWS with a long-lived access key. Remove AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY from its environment, run aws login --profile platform-operator, and set AWS_PROFILE=platform-control-plane.",
          ),
          { name: "LongLivedAwsKeyError" },
        ),
      );

      const result = await createTenantAndDeploy(null, formData(validAws));

      expect(result?.errors._form).toContain("long-lived access key");
      expect(result?.errors._form).toContain("AWS_PROFILE=platform-control-plane");
      expect(triggerDeployment).not.toHaveBeenCalled();
    });

    it("names the platform setting an operator forgot to configure", async () => {
      triggerDeployment.mockRejectedValue(
        new Error(
          "PLATFORM_CHATBOT_IMAGE_URI is not set. Should be the source image URI in your ECR, without a tag.",
        ),
      );

      const result = await createTenantAndDeploy(null, formData(validAws));

      expect(result?.errors._form).toContain("PLATFORM_CHATBOT_IMAGE_URI");
    });

    it("says the slug is taken instead of sending the operator to the server log", async () => {
      dbInsertReturning.mockRejectedValue(
        Object.assign(new Error('duplicate key value violates unique constraint "tenants_slug_unique"'), {
          code: "23505",
        }),
      );

      const result = await createTenantAndDeploy(null, formData(validAws));

      expect(result?.errors._form).toContain("already exists");
      expect(result?.errors._form).not.toContain("duplicate key value");
    });

    // Some drivers put the constraint name only in the message, not in a
    // `constraint` property. Misreading it as a slug clash would send the
    // operator off to rename a slug that was never the problem.
    it("recognises a reused tenant ID from the error message alone", async () => {
      dbInsertReturning.mockRejectedValue(
        Object.assign(new Error('duplicate key value violates unique constraint "tenants_pkey"'), {
          code: "23505",
        }),
      );

      const result = await createTenantAndDeploy(null, formData(validAws));

      expect(result?.errors._form).toContain("Reload the page");
      expect(result?.errors._form).not.toContain("slug");
    });

    it("tells the operator to reload when the wizard's tenant ID was already used", async () => {
      dbInsertReturning.mockRejectedValue(
        Object.assign(new Error('duplicate key value violates unique constraint "tenants_pkey"'), {
          code: "23505",
          constraint: "tenants_pkey",
        }),
      );

      const result = await createTenantAndDeploy(null, formData(validAzure));

      expect(result?.errors._form).toContain("Reload the page");
      expect(triggerDeployment).not.toHaveBeenCalled();
    });

    it("does not forward an unrecognised error's message to the browser", async () => {
      assumeTenantRole.mockRejectedValue(new Error("connect ECONNREFUSED 10.0.0.1:5432"));

      const result = await createTenantAndDeploy(null, formData(validAws));

      expect(result?.errors._form).toBeDefined();
      expect(result?.errors._form).not.toContain("ECONNREFUSED");
    });

    it("reports a failed deploy dispatch after the tenant row was written", async () => {
      triggerDeployment.mockRejectedValue(
        Object.assign(new Error("Not Found"), { name: "HttpError", status: 404 }),
      );

      const result = await createTenantAndDeploy(null, formData(validAws));

      expect(result?.deployed).toBeUndefined();
      expect(result?.errors._form).toContain("GitHub rejected the deployment dispatch");
    });
  });

  describe("successful submission", () => {
    it("assumes the tenant role and writes both secrets for an AWS + pinecone tenant, then returns the deployment", async () => {
      const result = await createTenantAndDeploy(null, formData(validAws));
      expect(result?.deployed).toEqual({
        tenantId: "tenant-1",
        deploymentId: "deploy-1",
        startedAt: "2026-01-01T00:00:00.000Z",
      });

      expect(assumeTenantRole).toHaveBeenCalledWith(
        expect.objectContaining({ roleArn: validAws.deploymentRoleArn, region: "us-east-1" }),
      );
      expect(writeTenantSecret).toHaveBeenCalledTimes(2); // llm key + pinecone key
      expect(ensureDocsSignerSecret).toHaveBeenCalledWith(
        expect.objectContaining({ roleArn: validAws.deploymentRoleArn, slug: "acme-co" }),
      );
      expect(generateDocsSignerSecret).not.toHaveBeenCalled();
      expect(triggerDeployment).toHaveBeenCalledWith(
        expect.objectContaining({ tenantId: "tenant-1", triggeredByUserId: "user-1" }),
      );
    });

    it("does not touch AWS APIs for an Azure tenant, and generates a docs-signer secret instead", async () => {
      const result = await createTenantAndDeploy(null, formData(validAzure));
      expect(result?.deployed).toBeDefined();

      expect(assumeTenantRole).not.toHaveBeenCalled();
      expect(writeTenantSecret).not.toHaveBeenCalled();
      expect(ensureDocsSignerSecret).not.toHaveBeenCalled();
      expect(generateDocsSignerSecret).toHaveBeenCalledWith();
      expect(triggerDeployment).toHaveBeenCalled();
    });

    // The thesis-level property of Azure onboarding: the platform stores
    // nothing that can sign in to the customer's subscription.
    it("stores no Azure credential, and creates the tenant under the ID its federated credential names", async () => {
      await createTenantAndDeploy(
        null,
        formData({ ...validAzure, azureClientSecret: "left-over-from-an-old-draft" }),
      );

      const row = insertedValues();
      expect(row.id).toBe(validAzure.tenantId);
      expect(Object.keys(row).filter((k) => /^azure/.test(k)).sort()).toEqual([
        "azureClientId",
        "azureRegion",
        "azureSubscriptionId",
        "azureTenantId",
      ]);
      expect(encryptSecret).not.toHaveBeenCalledWith("left-over-from-an-old-draft");
    });

    // The confused-deputy guard. Onboarding is the first time the platform
    // writes into the customer's account, so both of its role assumptions
    // must carry the tenant's ExternalId — a customer who applied the
    // condition would otherwise be locked out of their own onboarding.
    it("sends the tenant's ExternalId on both of onboarding's role assumptions", async () => {
      await createTenantAndDeploy(null, formData(validAws));

      expect(assumeTenantRole).toHaveBeenCalledWith(
        expect.objectContaining({ externalId: validAws.tenantId }),
      );
      expect(ensureDocsSignerSecret).toHaveBeenCalledWith(
        expect.objectContaining({ externalId: validAws.tenantId }),
      );
    });

    // The customer's trust policy names the ID the wizard showed them. A row
    // created under any other ID would send an ExternalId their policy
    // refuses, and the tenant could never deploy.
    it("creates an AWS tenant under the ID its trust policy's ExternalId names", async () => {
      await createTenantAndDeploy(null, formData(validAws));

      expect(insertedValues().id).toBe(validAws.tenantId);
    });

    it("refuses an AWS tenant without a tenant ID, before touching the customer's account", async () => {
      const result = await createTenantAndDeploy(null, formData({ ...validAws, tenantId: undefined }));

      expect(result?.errors.tenantId).toBeDefined();
      expect(assumeTenantRole).not.toHaveBeenCalled();
      expect(db.insert).not.toHaveBeenCalled();
    });

    it("writes only the LLM secret (not a Pinecone secret) for an AWS + pgvector tenant", async () => {
      const result = await createTenantAndDeploy(
        null,
        formData({ ...validAws, vectorStore: "pgvector", pineconeApiKey: undefined }),
      );
      expect(result?.deployed).toBeDefined();

      expect(writeTenantSecret).toHaveBeenCalledTimes(1);
    });

    it("deletes the wizard's draft row once the tenant it was for now exists", async () => {
      const result = await createTenantAndDeploy(
        null,
        formData({ ...validAws, draftId: "draft-1" }),
      );

      expect(result?.deployed).toBeDefined();
      expect(db.delete).toHaveBeenCalledWith(tenantDrafts);
    });

    it("does not touch tenantDrafts when the submission carries no draftId", async () => {
      const result = await createTenantAndDeploy(null, formData(validAws));

      expect(result?.deployed).toBeDefined();
      expect(db.delete).not.toHaveBeenCalled();
    });
  });

  describe("unrecognised fields", () => {
    // The wizard posts its whole value map as hidden inputs, so a stale key
    // left over from a resumed draft must not reach the insert.
    it("ignores form fields that are not part of the schema", async () => {
      const result = await createTenantAndDeploy(
        null,
        formData({ ...validAws, llmTemperature: "0.2", somethingRemoved: "x" }),
      );

      expect(result?.deployed).toBeDefined();
      expect(insertedValues()).not.toHaveProperty("llmTemperature");
      expect(insertedValues()).not.toHaveProperty("somethingRemoved");
    });
  });
});

describe("saveTenantDraft", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    authMock.mockResolvedValue({ user: { id: "user-1" } });
    dbInsertReturning.mockResolvedValue([
      { id: "draft-1", updatedAt: new Date("2026-01-01T00:00:00Z") },
    ]);
    dbUpdateReturning.mockResolvedValue([
      { id: "draft-1", updatedAt: new Date("2026-01-02T00:00:00Z") },
    ]);
  });

  it("redirects to /signin when there is no authenticated session", async () => {
    authMock.mockResolvedValue(null);

    await expect(saveTenantDraft(null, formData({ name: "Acme" }))).rejects.toThrow(
      "REDIRECT:/signin",
    );
    expect(db.insert).not.toHaveBeenCalled();
  });

  // The headline security property of this action: a draft has no deployment
  // behind it, so persisting a plaintext credential here would leak a real
  // customer secret into the control-plane database for no reason.
  it.each(["llmApiKey", "pineconeApiKey"] as const)(
    "never persists %s, even though it was submitted",
    async (secretField) => {
      await saveTenantDraft(
        null,
        formData({ name: "Acme", [secretField]: "super-secret-value" }),
      );

      expect(insertedValues().data).not.toHaveProperty(secretField);
    },
  );

  // The opposite of the secret fields above: the customer may already have
  // created a federated credential (Azure) or trust policy (AWS) naming this
  // ID, so a resumed draft that lost it would deploy under a new ID nothing
  // trusts.
  it("keeps the generated tenantId, which the customer's cloud trust may already name", async () => {
    await saveTenantDraft(
      null,
      formData({ name: "Acme", tenantId: "0b6f3c7e-9a1d-4a7e-8f53-2d1c6b9e4a10" }),
    );

    expect(insertedValues().data).toHaveProperty("tenantId", "0b6f3c7e-9a1d-4a7e-8f53-2d1c6b9e4a10");
  });

  // The field left the wizard with federation, but a tab still running the
  // previous wizard can submit one. Drafts keep every field they are not told
  // to strip, so without this the secret would be saved in plaintext.
  it("never persists an Azure client secret sent by an out-of-date wizard", async () => {
    await saveTenantDraft(
      null,
      formData({ name: "Acme", azureClientSecret: "pasted-into-an-old-tab" }),
    );

    expect(insertedValues().data).not.toHaveProperty("azureClientSecret");
  });

  it("excludes step and empty-string fields from the persisted data", async () => {
    // No draftId here on purpose — the insert path is what's under test, and
    // submitting one would route this into the update branch instead.
    await saveTenantDraft(null, formData({ name: "Acme", step: "2", domain: "" }));

    const data = insertedValues().data as Record<string, unknown>;
    expect(data).not.toHaveProperty("step");
    expect(data).not.toHaveProperty("domain");
    expect(data.name).toBe("Acme");
  });

  it("sets name to null when the form has no name field", async () => {
    await saveTenantDraft(null, formData({ slug: "acme-co" }));

    expect(insertedValues().name).toBeNull();
  });

  it.each([
    ["1", 1],
    ["5", 5],
    [undefined, 1],
    ["0", 1],
    ["6", 1],
    ["not-a-number", 1],
  ])("normalizes step %s to %i", async (rawStep, expectedStep) => {
    await saveTenantDraft(null, formData({ name: "Acme", step: rawStep }));

    expect(insertedValues().step).toBe(expectedStep);
  });

  it("inserts a new draft when no draftId is given", async () => {
    const result = await saveTenantDraft(null, formData({ name: "Acme" }));

    expect(db.insert).toHaveBeenCalled();
    expect(db.update).not.toHaveBeenCalled();
    expect(result).toEqual({ draftId: "draft-1", savedAt: "2026-01-01T00:00:00.000Z" });
  });

  it("updates an existing draft in place when draftId belongs to the session user", async () => {
    const result = await saveTenantDraft(
      null,
      formData({ name: "Acme Renamed", draftId: "draft-1" }),
    );

    expect(db.update).toHaveBeenCalledWith(tenantDrafts);
    expect(db.insert).not.toHaveBeenCalled();
    expect(updatedValues().name).toBe("Acme Renamed");
    expect(result).toEqual({ draftId: "draft-1", savedAt: "2026-01-02T00:00:00.000Z" });
  });

  it("falls through to an insert when the update matches no row (wrong owner or stale id)", async () => {
    dbUpdateReturning.mockResolvedValue([]);

    const result = await saveTenantDraft(
      null,
      formData({ name: "Acme", draftId: "someone-elses-draft" }),
    );

    expect(db.update).toHaveBeenCalled();
    expect(db.insert).toHaveBeenCalled();
    expect(result).toEqual({ draftId: "draft-1", savedAt: "2026-01-01T00:00:00.000Z" });
  });

  it("returns an error instead of throwing when the db operation fails", async () => {
    dbInsertReturning.mockRejectedValue(new Error("connection reset"));

    const result = await saveTenantDraft(null, formData({ name: "Acme" }));

    expect(result).toEqual({ error: "Could not save the draft. Your entries are still on this page." });
  });
});

describe("deleteTenantDraft", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    authMock.mockResolvedValue({ user: { id: "user-1" } });
  });

  it("redirects to /signin when there is no authenticated session", async () => {
    authMock.mockResolvedValue(null);

    await expect(deleteTenantDraft("draft-1")).rejects.toThrow("REDIRECT:/signin");
    expect(db.delete).not.toHaveBeenCalled();
  });

  it("deletes from the tenantDrafts table", async () => {
    await deleteTenantDraft("draft-1");

    expect(db.delete).toHaveBeenCalledWith(tenantDrafts);
  });
});

describe("checkSlugAvailable", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    authMock.mockResolvedValue({ user: { id: "user-1" } });
  });

  it("reports a slug no tenant has as available", async () => {
    await expect(checkSlugAvailable("acme-co")).resolves.toEqual({ available: true });
  });

  it("reports a slug another tenant has, and says why it cannot be reused", async () => {
    dbSelectLimit.mockResolvedValueOnce([{ id: "older-tenant" }]);

    const result = await checkSlugAvailable("acme-co");

    expect(result.available).toBe(false);
    expect(!result.available && result.reason).toMatch(/Slugs are permanent/);
  });

  it("says nothing about any slug without a session", async () => {
    authMock.mockResolvedValue(null);

    const result = await checkSlugAvailable("acme-co");

    expect(result.available).toBe(false);
    expect(db.select).not.toHaveBeenCalled();
  });
});

describe("checkDeploymentIdentity", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    authMock.mockResolvedValue({ user: { id: "user-1" } });
  });

  it("accepts an identity no tenant has used", async () => {
    await expect(checkDeploymentIdentity("azureClientId", "e837d9e4-5147-4215-985c-4387ba86acf4")).resolves.toEqual({
      available: true,
    });
  });

  it("refuses one another tenant used, and says what to paste instead", async () => {
    dbSelectLimit.mockResolvedValueOnce([{ slug: "kastriot-chatbot", deletedAt: new Date() }]);

    const result = await checkDeploymentIdentity("azureClientId", "b2ed660e-1508-439c-8f12-2187fb40d3db");

    expect(result.available).toBe(false);
    expect(!result.available && result.reason).toMatch(/"kastriot-chatbot", which has been deleted.*clientId output/);
  });

  // The field name arrives from the browser, so it cannot pick a column.
  it("looks up only the two identity columns", async () => {
    const result = await checkDeploymentIdentity("llmApiKeyEncrypted" as never, "anything");

    expect(result.available).toBe(false);
    expect(db.select).not.toHaveBeenCalled();
  });

  it("says nothing without a session", async () => {
    authMock.mockResolvedValue(null);

    const result = await checkDeploymentIdentity("deploymentRoleArn", "arn:aws:iam::111122223333:role/chatbot-client-deploy-acme");

    expect(result.available).toBe(false);
    expect(db.select).not.toHaveBeenCalled();
  });
});
